/**
 * Categorical palettes. GENERATED by build/gen-palettes.mjs - do not edit.
 *
 *     npm run palettes
 *
 * Why these and not d3.schemeCategory10: that scheme holds ten colours and
 * d3.scaleOrdinal RECYCLES them, so an eleventh category is drawn in exactly
 * the colour of the first with nothing said. It also collides for colour-blind
 * readers before it runs out - measured at 1.6 CIEDE2000 under protanopia at
 * ten categories, below the ~2.3 just-noticeable difference.
 *
 * `nameable` is the default. Minimum pairwise CIEDE2000, worst case across
 * normal, protanopia, deuteranopia and tritanopia:
 *
 *     n=16  9.4      n=24  7.2      n=32  5.6      n=50  4.5
 *
 * with every colour above the naming-confusion threshold. See
 * docs/ai/COLOR-CATEGORICAL.md.
 */
import * as d3 from "d3";

/** Maximally separated AND nameable. The default. */
export const nameable = [
  "#5c3f3a",
  "#aadcff",
  "#fea23f",
  "#583df9",
  "#91816b",
  "#3799dd",
  "#b9130a",
  "#bcba9d",
  "#9f4d8b",
  "#dd5712",
  "#433d8e",
  "#f9c7d5",
  "#716b49",
  "#c09563",
  "#792460",
  "#7e5cff",
  "#75b2e8",
  "#fd66b5",
  "#367dba",
  "#a47b4a",
  "#8ba48e",
  "#5a52b9",
  "#3c29cc",
  "#4d471e",
  "#755751",
  "#eba2d0",
  "#49e25d",
  "#d88c18",
  "#f81c7c",
  "#c53ab9",
  "#7b387c",
  "#94472c",
  "#619119",
  "#96669e",
  "#dada22",
  "#7253e1",
  "#82755e",
  "#5f503b",
  "#6e5294",
  "#8898fe",
  "#b98645",
  "#4d84e3",
  "#e55cba",
  "#85957c",
  "#e692ad",
  "#806459",
  "#d25796",
  "#553bc4",
  "#9d6b44",
  "#436824",
];

/** Maximally separated, ignoring whether a colour has a name. */
export const distinct = [
  "#5d3e47",
  "#afe523",
  "#f65bfd",
  "#2a21e3",
  "#7e8948",
  "#eacce1",
  "#069492",
  "#8d0e05",
  "#39d193",
  "#594b7c",
  "#bb25ff",
  "#5f7e6e",
  "#ab9f11",
  "#f1249f",
  "#98414a",
  "#a8a9c5",
  "#fdaafd",
  "#699c7d",
  "#6d576d",
  "#4c3699",
  "#90c3b5",
  "#ccdc82",
  "#bf390f",
  "#755db4",
  "#abb063",
  "#8f8cc2",
  "#74302d",
  "#8ee6c2",
  "#514157",
  "#6549cb",
  "#8a6f82",
  "#7d525c",
  "#fd9e9c",
  "#17b1a9",
  "#c7ba42",
  "#be6f10",
  "#9e7c68",
  "#b90933",
  "#e58be6",
  "#776484",
  "#f1559d",
  "#81a876",
  "#6584c9",
  "#99565f",
  "#31eedb",
  "#fc1658",
  "#5871db",
  "#583df9",
  "#5d612d",
  "#806271",
];

/**
 * mokole.com's generator: farthest-point over the X11 named colours, scored on
 * Euclidean CIELAB for normal vision. Vivid, and the best of the field on that
 * metric - but colour blindness is not in its objective, and its limegreen and
 * tomato are 0.7 apart under deuteranopia.
 */
export const mokole = [
  "#d3d3d3",
  "#2f4f4f",
  "#556b2f",
  "#6b8e23",
  "#a0522d",
  "#a52a2a",
  "#2e8b57",
  "#228b22",
  "#708090",
  "#483d8b",
  "#008b8b",
  "#4682b4",
  "#000080",
  "#d2691e",
  "#9acd32",
  "#32cd32",
  "#daa520",
  "#8fbc8f",
  "#8b008b",
  "#d2b48c",
  "#48d1cc",
  "#9932cc",
  "#ff4500",
  "#ff8c00",
  "#ffd700",
  "#0000cd",
  "#00ff00",
  "#00fa9a",
  "#dc143c",
  "#00bfff",
  "#f4a460",
  "#0000ff",
  "#a020f0",
  "#adff2f",
  "#ff6347",
  "#ff00ff",
  "#1e90ff",
  "#db7093",
  "#f0e68c",
  "#fa8072",
  "#ffff54",
  "#dda0dd",
  "#90ee90",
  "#87ceeb",
  "#ff1493",
  "#7b68ee",
  "#ee82ee",
  "#7fffd4",
  "#ff69b4",
  "#ffc0cb",
];

/** What Navio drew before 0.3.0. Ten colours, and it recycles past them. */
export const category10 = d3.schemeCategory10.slice();

/** Best salience and least name overlap of the palettes Heer & Stone measured. */
export const tableau10 = d3.schemeTableau10.slice();

/**
 * Sampled at i/n rather than d3.quantize's i/(n-1). Rainbow and Sinebow are
 * CYCLICAL - t=0 and t=1 are the same colour - so quantize puts an exact
 * duplicate at the ends, which is the bug these palettes exist to avoid.
 */
export const rainbow = (n) =>
  d3.range(n).map((i) => d3.interpolateRainbow(i / n));
export const sinebow = (n) =>
  d3.range(n).map((i) => d3.interpolateSinebow(i / n));

/** Built for sequential data. Included because it is the obvious thing to try. */
export const turbo = (n) => d3.quantize(d3.interpolateTurbo, n);

export const palettes = {
  nameable,
  distinct,
  mokole,
  category10,
  tableau10,
  rainbow,
  sinebow,
  turbo,
};
