/**
 * What Navio can be configured with, described once.
 *
 * This is the single source for three things that used to be separate, or
 * missing entirely:
 *
 *   1. the settings panel, which builds its controls from the entries marked
 *      `control` (see LIVE_OPTIONS / LIVE_COLOURS in navio.js);
 *   2. `navio.describe()`, for anything reading the API at runtime;
 *   3. `docs/ai/API.md`, generated by build/gen-api-docs.js.
 *
 * Before this existed the only written descriptions of Navio's options lived
 * inside the panel's slider table - 18 of 51 options - and existed to render
 * tooltips. Nothing told a reader, human or otherwise, what the other 33 did.
 *
 * Two tests keep it honest, and both matter more than the file itself:
 *   - every key on the instance has an entry here, so an option cannot be added
 *     without describing it;
 *   - every `default` here matches a real instance's value, so the description
 *     cannot drift from the code it describes.
 *
 * `default` is omitted where the value is a function or a d3 scheme; those
 * carry `defaultText` for the docs instead, since there is nothing JSON-safe
 * to compare against.
 */
export const PARAMS = [
  // ---------------------------------------------------------------- layout
  {
    key: "height",
    type: "number",
    default: 600,
    section: "Layout",
    label: "Size along records",
    hint: "The widget's extent along the RECORD axis - screen height when horizontal, width when vertical. More room means fewer rows share a pixel line.",
    control: "range",
    min: 100,
    max: 1200,
    step: 20,
  },
  {
    key: "orientation",
    type: "string",
    default: "horizontal",
    values: ["horizontal", "vertical"],
    section: "Layout",
    label: "Orientation",
    hint: 'Which way the two axes run. "horizontal" puts attributes across and records down; "vertical" transposes both. All geometry goes through toXY, so everything follows.',
  },
  {
    key: "attribWidth",
    type: "number",
    default: 15,
    section: "Layout",
    label: "Column width",
    hint: "How wide each column is drawn. Narrow columns fit more attributes on screen; wide ones make individual values easier to compare.",
    control: "range",
    min: 4,
    max: 60,
    step: 1,
  },
  {
    key: "levelsSeparation",
    type: "number",
    default: 40,
    section: "Layout",
    label: "Level gap",
    hint: "Horizontal gap between drill-down levels. The filter chips are drawn in this gap, so a wider gap gives them more room.",
    control: "range",
    min: 0,
    max: 200,
    step: 5,
  },
  {
    key: "margin",
    type: "number",
    default: 10,
    section: "Layout",
    label: "Margin",
    hint: "Blank space around the drawing, inside the widget.",
    control: "range",
    min: 0,
    max: 100,
    step: 5,
  },
  {
    key: "x0",
    type: "number",
    default: 0,
    section: "Layout",
    label: "Left offset",
    hint: "Offset of the whole drawing from the container's left edge.",
    control: "range",
    min: 0,
    max: 200,
    step: 5,
  },
  {
    key: "y0",
    type: "number",
    default: 100,
    section: "Layout",
    label: "Top offset",
    hint: "Room for the rotated column headers, before the records start. Measured from the labels by default; moving this slider takes that over and keeps whatever you set.",
    control: "range",
    min: 0,
    max: 300,
    step: 5,
  },
  {
    key: "autoHeaderSpace",
    type: "boolean",
    default: true,
    section: "Layout",
    label: "Measure the header band",
    hint: "Size y0 from the labels actually drawn, on every update. Off means y0 is yours. Note the band is ADDED to height rather than taken out of it, so the data area is height either way.",
  },
  {
    key: "headerMaxSpace",
    type: "number",
    default: 140,
    section: "Layout",
    label: "Header band cap",
    hint: "The most the header band will reserve. Past this the labels still draw in full, but the extra hangs above the widget instead of growing it - and what it hangs over, it takes clicks from. Ignored in vertical orientation, which never spills.",
  },
  {
    key: "theme",
    type: "string",
    default: "auto",
    values: ["auto", "light", "dark"],
    section: "Layout",
    label: "Theme",
    hint: "Which way the widget's CHROME is coloured - labels, counts, borders, the panel, the tooltip. \"auto\" follows the page's prefers-color-scheme and keeps following it. The DATA colours never follow it: inverting a categorical scale would change what a colour means. The widget stays transparent in every theme, so it sits on the page's own background.",
  },
  // --------------------------------------------------------------- headers
  {
    key: "showAttribTitles",
    type: "boolean",
    default: true,
    section: "Headers",
    label: "Show column headers",
    hint: "Draw the column header labels. Off costs no header band at all.",
  },
  {
    key: "attribRotation",
    type: "number",
    default: -45,
    section: "Headers",
    label: "Header angle",
    hint: "Angle of the column headers, in degrees. 0 is horizontal and -90 is vertical; steeper angles fit longer names above narrow columns. Ignored in vertical orientation, where labels are upright.",
    control: "range",
    min: -90,
    max: 0,
    step: 5,
  },
  {
    key: "attribFontSize",
    type: "number",
    default: 13,
    section: "Headers",
    label: "Header font",
    hint: "Size of the column header labels. Capped by the column width, so widening a column can be what actually makes a header legible.",
    control: "range",
    min: 6,
    max: 24,
    step: 1,
  },
  {
    key: "attribFontSizeSelected",
    type: "number",
    default: 32,
    section: "Headers",
    label: "Header font (hover)",
    hint: "Size a header grows to while the pointer is over it, so a rotated label can be read without changing the layout.",
    control: "range",
    min: 6,
    max: 32,
    step: 1,
  },
  {
    key: "showSelectedAttrib",
    type: "boolean",
    default: true,
    section: "Headers",
    label: "Show the selected column",
    hint: "Draw the derived column marking which rows are selected.",
  },
  {
    key: "showSequenceIDAttrib",
    type: "boolean",
    default: true,
    section: "Headers",
    label: "Show the sequence column",
    hint: 'Draw the derived "sequential Index" column. Worth knowing that its label is the widest one on a default widget, so it sets the header band on its own however short your own attribute names are.',
  },
  // -------------------------------------------------------------- filtering
  {
    key: "nestedFilters",
    type: "boolean",
    default: true,
    section: "Filtering",
    label: "Nested filters",
    hint: "Each filter opens a new level showing the rows that survived it. Off keeps a single level and re-filters it in place - a second, much less travelled code path; see docs/ai/FILTERING-MODEL.md.",
  },
  {
    key: "clickTolerance",
    type: "number",
    default: 4,
    section: "Filtering",
    label: "Click tolerance",
    hint: "How far the pointer may drift during a click and still count as a click rather than a range selection. Raise it if selecting a single value is difficult.",
    control: "range",
    min: 0,
    max: 20,
    step: 1,
  },
  {
    key: "filterFontSize",
    type: "number",
    default: 8,
    section: "Filtering",
    label: "Filter font",
    hint: "Size of the filter chips under the levels.",
    control: "range",
    min: 6,
    max: 20,
    step: 1,
  },
  {
    key: "fmtCounts",
    type: "function",
    defaultText: 'd3.format(",.0d")',
    section: "Filtering",
    label: "Count format",
    hint: "Formats the per-level record counts. Any (number) -> string will do.",
  },
  // ------------------------------------------------------------------ rows
  {
    key: "divisionsThreshold",
    type: "number",
    default: 4,
    section: "Rows",
    label: "Row divider threshold",
    hint: "How many pixels a row must occupy before dividing lines are drawn between rows. Below this the lines would be thicker than the rows.",
    control: "range",
    min: 0,
    max: 20,
    step: 1,
  },
  {
    key: "divisionsColor",
    type: "colour | null",
    default: null,
    section: "Rows",
    label: "Row dividers",
    hint: "Colour of the lines drawn between rows when they are tall enough. null follows the theme; a colour you set is used in both.",
    control: "color",
  },
  {
    key: "levelConnectionsColor",
    type: "colour",
    default: "rgba(205, 220, 163, 0.5)",
    section: "Rows",
    label: "Level connections",
    hint: "Colour of the ribbons linking a level to the rows it came from.",
    control: "color",
  },
  {
    key: "linkColor",
    type: "colour",
    default: "#ccc",
    section: "Rows",
    label: "Links",
    hint: "Colour of the curves drawn for links passed via nv.links().",
    control: "color",
  },
  {
    key: "nullColor",
    type: "colour",
    default: "#ffedfd",
    section: "Rows",
    label: "Null colour",
    hint: "Colour for a missing value, in every scale type. The same in both themes on purpose: a gap is not a value, and it should look like the same gap on a dark page as on a light one.",
  },
  // --------------------------------------------------------------- tooltip
  {
    key: "tooltipBgColor",
    type: "colour | null",
    default: null,
    section: "Tooltip",
    label: "Tooltip background",
    hint: "Background of the hover tooltip. null follows the theme; a colour you set is used in both.",
    control: "color",
    needsData: true,
  },
  {
    key: "tooltipFontSize",
    type: "number",
    default: 12,
    section: "Tooltip",
    label: "Tooltip font",
    hint: "Font size inside the hover tooltip. Read once, when the tooltip is built.",
  },
  {
    key: "tooltipMargin",
    type: "number",
    default: 50,
    section: "Tooltip",
    label: "Tooltip offset",
    hint: "How far the tooltip sits from the pointer.",
  },
  {
    key: "tooltipArrowSize",
    type: "number",
    default: 10,
    section: "Tooltip",
    label: "Tooltip arrow",
    hint: "Size of the tooltip's arrow, in pixels.",
  },
  // ------------------------------------------------------------- attributes
  {
    key: "id",
    type: "string",
    default: "__seqId",
    section: "Attributes",
    label: "Row id field",
    hint: "Which field identifies a row. Defaults to the row's position, which is enough until rows are re-sorted or linked - set it to a real key for links, and for a selection that survives sorting.",
  },
  {
    key: "maxNumDistinctForCategorical",
    type: "number",
    default: 30,
    section: "Attributes",
    label: "Categorical threshold",
    hint: "addAllAttribs calls an attribute categorical below this many distinct values.",
  },
  {
    key: "maxNumDistinctForOrdered",
    type: "number",
    default: 90,
    section: "Attributes",
    label: "Ordered threshold",
    hint: "addAllAttribs calls an attribute ordered below this many distinct values, and text above it. Set to Infinity to never choose text.",
  },
  {
    key: "howManyItemsShouldSearchForNotNull",
    type: "number",
    default: 100,
    section: "Attributes",
    label: "Type-sniffing depth",
    hint: "How many rows to look through for a non-null value when guessing an attribute's type.",
  },
  {
    key: "addAllAttribsRecursionLevel",
    type: "number",
    defaultText: "Infinity",
    section: "Attributes",
    label: "Nesting depth",
    hint: "How deep addAllAttribs descends into nested objects.",
  },
  {
    key: "addAllAttribsIncludeObjects",
    type: "boolean",
    default: false,
    section: "Attributes",
    label: "Include objects",
    hint: "Let addAllAttribs make a column out of an object-valued field.",
  },
  {
    key: "addAllAttribsIncludeArrays",
    type: "boolean",
    default: false,
    section: "Attributes",
    label: "Include arrays",
    hint: "Let addAllAttribs make a column out of an array-valued field.",
  },
  {
    key: "digitsForText",
    type: "number",
    default: 2,
    section: "Attributes",
    label: "Text digits",
    hint: "How many leading characters a text attribute is bucketed by.",
  },
  {
    key: "digitsForObjects",
    type: "number",
    defaultText: "Infinity",
    section: "Attributes",
    label: "Object digits",
    hint: "As digitsForText, for stringified objects and arrays.",
  },
  {
    key: "stringify",
    type: "function",
    defaultText: "JSON.stringify",
    section: "Attributes",
    label: "Stringify",
    hint: "Turns object values into strings for bucketing. Pass `d => d` to make this cheap when you know the values are already strings.",
  },
  // ---------------------------------------------------------------- colours
  {
    key: "defaultColorInterpolator",
    type: "function",
    defaultText: "d3.interpolateBlues",
    section: "Colours",
    label: "Sequential scheme",
    hint: "Interpolator for sequential (numeric) attributes.",
  },
  {
    key: "defaultColorInterpolatorDate",
    type: "function",
    defaultText: "d3.interpolatePurples",
    section: "Colours",
    label: "Date scheme",
    hint: "Interpolator for date attributes.",
  },
  {
    key: "defaultColorInterpolatorDiverging",
    type: "function",
    defaultText: "d3.interpolateBrBG",
    section: "Colours",
    label: "Diverging scheme",
    hint: "Interpolator for diverging attributes - chosen automatically only when the data actually crosses zero.",
  },
  {
    key: "defaultColorInterpolatorOrdered",
    type: "function",
    defaultText: "d3.interpolateOranges",
    section: "Colours",
    label: "Ordered scheme",
    hint: "Interpolator for ordered attributes.",
  },
  {
    key: "defaultColorInterpolatorText",
    type: "function",
    defaultText: "d3.interpolateGreys",
    section: "Colours",
    label: "Text scheme",
    hint: "Interpolator for text attributes.",
  },
  {
    key: "defaultColorInterpolatorObject",
    type: "function",
    defaultText: "d3.interpolateGreens",
    section: "Colours",
    label: "Object scheme",
    hint: "Interpolator for object and array attributes.",
  },
  {
    key: "defaultColorRangeBoolean",
    type: "array",
    default: ["#a1d76a", "#e9a3c9", "white"],
    section: "Colours",
    label: "Boolean colours",
    hint: "Colours for true, false and null, in that order.",
  },
  {
    key: "defaultColorRangeSelected",
    type: "array",
    default: ["white", "#b5cf6b"],
    section: "Colours",
    label: "Selected colours",
    hint: "Colours for unselected and selected rows in the derived selected column.",
  },
  {
    key: "defaultColorCategorical",
    type: "array | function",
    defaultText: "navio.palettes.nameable",
    section: "Colours",
    label: "Categorical scheme",
    hint: "Palette for categorical attributes: an array of colours, or a function (n) => colours called with the number of categories. navio.palettes holds the built-ins - nameable (the default, 50 colours that stay distinguishable under colour blindness and can all be named), distinct, mokole, category10 (the pre-0.3.0 look), tableau10, turbo, rainbow, sinebow. Too few colours for the data warns rather than silently repeating.",
  },
  // --------------------------------------------------------- settings panel
  {
    key: "settings",
    type: "boolean",
    default: true,
    section: "Settings panel",
    label: "Show the gear",
    hint: "Whether the settings panel and its gear button exist at all. Read once, inside data().",
  },
  {
    key: "settingsPlacement",
    type: "string",
    default: "below",
    values: ["below", "beside", "over"],
    section: "Settings panel",
    label: "Panel placement",
    hint: "Where the panel opens relative to the widget. A modal placement was built and removed: it centres in the VIEWPORT, so with two Navios the panel appeared nowhere near the one it belonged to.",
  },
  {
    key: "settingsMaxAttribRows",
    type: "number",
    default: 10,
    section: "Settings panel",
    label: "Attribute rows",
    hint: "Past this many columns the attribute list scrolls inside its own box rather than pushing the rest of the panel below the fold.",
  },
  {
    key: "attribPicker",
    type: "function",
    default: null,
    section: "Settings panel",
    label: "Attribute picker",
    hint: "Replace the panel's attribute list. (names, {value, onChange, move, instanceId, types, getType, setType, canSetType}) -> HTMLElement.",
  },
  {
    key: "settingsKey",
    type: "string",
    defaultText: "undefined",
    section: "Settings panel",
    label: "Settings key",
    hint: "Where panel settings are remembered in localStorage. null turns persistence off. Undefined means the key is derived from the page and the CONTAINER'S id - and with no id there is no key, so nothing is stored: a per-page construction counter was tried and swapped two widgets' settings whenever they were built in a different order.",
  },
  // ------------------------------------------------------------------ debug
  {
    key: "DEBUG",
    type: "boolean",
    default: false,
    section: "Debug",
    label: "Debug",
    hint: "Trace internals to the console. Inherited from navio.DEBUG at construction, so set THAT before constructing to catch the first data() call.",
  },
];

/**
 * The public methods, for a reader who has the options but no idea how to
 * drive the thing. Signatures are the real ones; summaries say what the call
 * is FOR, not what it is called.
 */
export const METHODS = [
  {
    name: "data",
    signature: "data(rows) -> nv | rows",
    summary:
      "Set the rows to display, or read them back. Navio never writes to your rows.",
  },
  {
    name: "addAllAttribs",
    signature: "addAllAttribs(names?) -> nv",
    summary:
      "Add a column per field, guessing each type. Usually the only setup call needed after data().",
  },
  {
    name: "id",
    signature: "id(field) -> nv | field",
    summary:
      "Name the field that identifies a row. Needed for links and for stable selection across re-sorts.",
  },
  {
    name: "addSequentialAttrib",
    signature: "addSequentialAttrib(attrib, scale?) -> nv",
    summary:
      "Add one column with an explicit type. Also: Categorical, Ordered, Date, Diverging, Text, Boolean, Object.",
  },
  {
    name: "getFilters",
    signature: "getFilters() -> filters[][]",
    summary:
      "The filter chain, one array per level. This is what to bind Navio-to-Navio on.",
  },
  {
    name: "setFilters",
    signature: "setFilters(filters[][]) -> nv",
    summary: "Rebuild the filter chain, reproducing a saved drill-down.",
  },
  {
    name: "getSelected",
    signature: "getSelected() -> rows",
    summary:
      "The rows currently selected. This - not the filter chain - is what NavioWidget.value carries.",
  },
  {
    name: "isSelected",
    signature: "isSelected(rowOrIndex) -> boolean",
    summary:
      "Is this row selected? Use this rather than looking for a property on the row; Navio keeps selection in a side table.",
  },
  {
    name: "setSelectedRows",
    signature: "setSelectedRows(rows) -> nv",
    summary: "Select exactly these rows.",
  },
  {
    name: "getRowsAtLevel",
    signature: "getRowsAtLevel(level = 0) -> rows",
    summary: "The rows that survived down to a given level of the chain.",
  },
  {
    name: "sortBy",
    signature: "sortBy(attrib, desc = false, level?) -> nv",
    summary:
      "Sort a level. Deliberately does not change which rows are selected - see docs/ai/FILTERING-MODEL.md.",
  },
  {
    name: "setAttribVisible",
    signature: "setAttribVisible(attrib, visible = true) -> nv",
    summary: "Show or hide one column, by name or by attribute value.",
  },
  {
    name: "getHiddenAttribs",
    signature: "getHiddenAttribs() -> names",
    summary:
      "Which columns are hidden. setHiddenAttribs(names) replaces the set.",
  },
  {
    name: "setAttribType",
    signature: "setAttribType(attrib, type) -> nv",
    summary:
      "Re-type a column after the fact - when the guess was wrong, or a numeric code is really a category.",
  },
  {
    name: "getSettings",
    signature: "getSettings() -> object",
    summary:
      "The panel's state as plain JSON. setSettings(cfg) applies it, and deliberately leaves filters and selection alone.",
  },
  {
    name: "getOptions",
    signature: "getOptions() -> object",
    summary:
      "Every option and its current value, in the shape the constructor accepts.",
  },
  {
    name: "setOptions",
    signature: "setOptions(options) -> nv",
    summary:
      "Apply several options at once, in an order that works - some are read only once.",
  },
  {
    name: "onChange",
    signature: "onChange(fn) -> nv",
    summary: "Call fn whenever the selection changes.",
  },
  {
    name: "links",
    signature: "links(links) -> nv | links",
    summary:
      "Draw curves between rows. Endpoints are resolved on every redraw, because d3-force rewrites them in place.",
  },
  {
    name: "update",
    signature: "update(opts?) -> nv",
    summary: "Redraw. hardUpdate() also rebuilds the scales.",
  },
  {
    name: "destroy",
    signature: "destroy() -> nv",
    summary:
      "Remove everything Navio added, including its listeners on body and the class it put on your container.",
  },
];
